platform: linux
image_resource:
  type: registry-image
  source:
    repository: cryogenics/essentials
    tag: 0.1.29
inputs:
  - name: disaster-recovery-acceptance-tests
  - name: integration-configs
  - name: cf-deployment-env
outputs:
  - name: updated-integration-configs
params:
  CF_DEPLOYMENT_NAME: cf
  INTEGRATION_CONFIG_FILE_PATH: ci/integration_config.json
  SYSTEM_DOMAIN:
  JUMPBOX_PRIVATE_KEY:
  CREDHUB_CLIENT:
  CREDHUB_SECRET:
  CREDHUB_CA_CERT:
  CREDHUB_SERVER:
  CREDHUB_PROXY:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_ALL_PROXY:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
run:
  path: disaster-recovery-acceptance-tests/ci/tasks/update-integration-config/task.sh
