platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks
    tag: latest

inputs:
- name: bbl-state
- name: disaster-recovery-acceptance-tests
- name: integration-configs

outputs:
- name: updated-integration-configs

params:
  BBL_STATE_DIR: bbl-state
  CF_DEPLOYMENT_NAME: cf
  INTEGRATION_CONFIG_FILE_PATH: ci/integration_config.json
  SYSTEM_DOMAIN:

run:
  path: disaster-recovery-acceptance-tests/ci/tasks/update-integration-config/task.sh
