platform: linux
image_resource:
  type: registry-image
  source:
    repository: cryogenics/essentials
    tag: 0.1.42
inputs:
  - name: disaster-recovery-acceptance-tests
    path: src/github.com/cloudfoundry/disaster-recovery-acceptance-tests
  - name: bbr-binary-release
  - name: drats-integration-config
params:
  CONFIG_FILE_PATH: drats_integration_config.json
  CF_DIAL_TIMEOUT:
run:
  path: src/github.com/cloudfoundry/disaster-recovery-acceptance-tests/ci/tasks/drats-with-integration-config/task.sh
