---
vault_creds: &vault_creds
  url: ((vault/server.url))
  role_id: ((vault/resource_credentials.role_id))
  secret_id: ((vault/resource_credentials.secret_id))

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

- name: vault
  type: docker-image
  source:
    repository: wfernandes/vault-resource
    tag: latest

resources:
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
    tag_filter: v12.*

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment.git
    branch: main

- name: disaster-recovery-acceptance-tests
  type: pull-request
  source:
    repository: cloudfoundry-incubator/disaster-recovery-acceptance-tests
    access_token: ((github.access_token))

- name: bbr-binary-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: bosh-backup-and-restore
    access_token: ((github.access_token))

- name: bbl-state
  type: vault
  source:
    <<: *vault_creds
    path: /concourse/bosh-backup-restore/drats/bbl-state
    tarball: true

jobs:

- name: set-pipeline
  plan:
    - get: disaster-recovery-acceptance-tests
      trigger: true
    - set_pipeline: drats
      file: disaster-recovery-acceptance-tests/ci/pipelines/drats/pipeline.yml

  ## DEPLOY CF

- name: deploy-cf-prs
  serial: true
  serial_groups: [drats-prs]
  plan:
  - in_parallel:
    - get: disaster-recovery-acceptance-tests
      version: every
      passed: [set-pipeline]
      trigger: true
    - get: cf-deployment
    - get: bbl-state
    - get: cf-deployment-concourse-tasks
  - load_var: system_domain
    file: bbl-state/bbl-state.json
    format: json
  - task: deploy-cf
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      ops-files: cf-deployment
    params:
      SYSTEM_DOMAIN: ((.:system_domain.lb.domain))
      OPS_FILES: "operations/scale-to-one-az.yml operations/use-compiled-releases.yml operations/backup-and-restore/enable-backup-restore.yml operations/enable-nfs-volume-service.yml operations/experimental/disable-interpolate-service-bindings.yml operations/experimental/enable-traffic-to-internal-networks.yml operations/experimental/enable-smb-volume-service.yml operations/backup-and-restore/skip-backup-restore-droplets-and-packages.yml"
      BBL_STATE_DIR: .
  - task: wait-for-cf-api
    file: disaster-recovery-acceptance-tests/ci/tasks/wait-for-cf-api/task.yml
    params:
      CF_API_URL: https://api.((.:system_domain.lb.domain))
      CF_UAA_URL: https://uaa.((.:system_domain.lb.domain))
  - task: bosh-run-errand-nfsbrokerpush
    file: cf-deployment-concourse-tasks/run-errand/task.yml
    params:
      ERRAND_NAME: nfsbrokerpush
      BBL_STATE_DIR: .
  - task: bosh-run-errand-smbbrokerpush
    file: cf-deployment-concourse-tasks/run-errand/task.yml
    params:
      ERRAND_NAME: smbbrokerpush
      BBL_STATE_DIR: .
  - task: bosh-cleanup
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    params:
      BBL_STATE_DIR: .
### RUN TESTS

- name: run-drats-prs
  serial: true
  serial_groups: [drats-prs]
  plan:
  - in_parallel:
    - get: cf-deployment
      passed: [deploy-cf-prs]
    - get: disaster-recovery-acceptance-tests
      trigger: true
      passed: [deploy-cf-prs]
      version: every
    - get: bbr-binary-release
    - get: bbl-state
  - load_var: system_domain
    file: bbl-state/bbl-state.json
    format: json
  - put: disaster-recovery-acceptance-tests
    params:
      path: disaster-recovery-acceptance-tests
      status: pending
      context: drats
  - task: unit-tests
    file: disaster-recovery-acceptance-tests/ci/tasks/unit-tests/task.yml
    params:
      GITHUB_SSH_KEY: ((github.ssh_key))
    on_failure:
      put: disaster-recovery-acceptance-tests
      params:
        path: disaster-recovery-acceptance-tests
        status: failure
        context: drats
  - task: create-integration-config
    file: disaster-recovery-acceptance-tests/ci/tasks/credhub-compatible/update-integration-config/task.yml
    input_mapping:
      integration-configs: disaster-recovery-acceptance-tests
    params:
      BBL_STATE_DIR: .
      SYSTEM_DOMAIN: ((.:system_domain.lb.domain))
  - task: acceptance-tests
    file: disaster-recovery-acceptance-tests/ci/tasks/drats-with-integration-config/task.yml
    privileged: true
    input_mapping:
      drats-integration-config: updated-integration-configs
    params:
      CONFIG_FILE_PATH: ci/integration_config.json
      CF_DIAL_TIMEOUT: 300
    on_failure:
      put: disaster-recovery-acceptance-tests
      params:
        path: disaster-recovery-acceptance-tests
        status: failure
        context: drats
    on_success:
      put: disaster-recovery-acceptance-tests
      params:
        path: disaster-recovery-acceptance-tests
        status: success
        context: drats

## Delete cf deployments
- name: delete-cf-prs
  serial: true
  serial_groups: [drats-prs]
  plan:
  - in_parallel:
    - get: cf-deployment
      passed: [run-drats-prs]
    - get: disaster-recovery-acceptance-tests
      trigger: true
      passed: [run-drats-prs]
    - get: cf-deployment-concourse-tasks
    - get: bbl-state
  - task: bosh-delete-deployment
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    params:
      BBL_STATE_DIR: .

