platform: linux
image_resource:
  type: registry-image
  source:
    repository: cryogenics/essentials
    tag: 0.1.53
inputs:
  - name: disaster-recovery-acceptance-tests
    path: src/github.com/cloudfoundry/disaster-recovery-acceptance-tests
run:
  path: src/github.com/cloudfoundry/disaster-recovery-acceptance-tests/ci/tasks/unit-tests/task.sh
params:
  GITHUB_SSH_KEY:
