platform: linux
image_resource:
  type: registry-image
  source:
    repository: cryogenics/essentials
    tag: 0.1.51
inputs:
  - name: disaster-recovery-acceptance-tests
    path: src/github.com/cloudfoundry/disaster-recovery-acceptance-tests
  - name: bbr-binary-release
params:
  CF_DEPLOYMENT_NAME:
  CF_ADMIN_USERNAME:
  CF_ADMIN_PASSWORD:
  CF_API_URL:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_CA_CERT:
  BOSH_ENVIRONMENT:
  BOSH_GW_USER:
  BOSH_GW_HOST:
  BOSH_GW_PRIVATE_KEY:
  SSH_DESTINATION_CIDR:
  FOCUSED_SUITE_NAME:
  SKIP_SUITE_NAME:
  DEFAULT_TIMEOUT_MINS:
  NFS_SERVICE_NAME:
  NFS_PLAN_NAME:
  NFS_BROKER_USER:
  NFS_BROKER_PASSWORD:
  NFS_BROKER_URL:
  SMB_SERVICE_NAME:
  SMB_PLAN_NAME:
  SMB_BROKER_USER:
  SMB_BROKER_PASSWORD:
  SMB_BROKER_URL:
  DELETE_AND_REDEPLOY_CF: false
  CF_CREDHUB_CLIENT:
  CF_CREDHUB_SECRET:
run:
  path: src/github.com/cloudfoundry/disaster-recovery-acceptance-tests/ci/tasks/drats/task.sh
